### ISSUE TITLE
Footnotes in titles don't work in certain cases

### ISSUE THREAD

**Issue by ldweeks** [warhornmedia/style-guide#1]
Your directions [here](https://warhornmedia.github.io/style-guide/warhorn-classics-books.html#footnotes) about adding footnotes in titles doesn't work. Every time I added a footnote to the title [here](https://warhornmedia.github.io/buchanan-doctrine-of-justification/001-History-of-the-Doctrine-in-the-Old-Testament.html), I get an error.

1. If I create a footnote for the title of that book part to mimic the printed book, and I number the footnotes in the entire file (which spans sections) consecutively, I get an error and the book doesn't build.
2. If I move that footnote into body text, but still number all footnotes consecutively across the file, everything works as I would expect.
3. If I restart the numbering at each new section, then the book builds and the link to the footnotes work as expected, but the text of footnotes #1 and #2 match the text of the SECOND #1, and the text of the first #1 is just gone.

**Comment by jtbayly** [comment]
Footnotes within a single Rmd file *must have unique names. That should be added as a note somewhere in the docs. 

I did test putting a footnote on a chapter title and it worked, so I’m not sure why it won’t work for you. Can you use a shorter footnote for testing and share your code here?

**Comment by ldweeks** [comment]
I added your note to the docs about footnotes needing to he unique in each Rmd file.

And after more testing, it appears that if you add a footnote to a heading, **and** the footnote has multiple paragraphs, the build fails with the following errors:

```
output file: Buchanan-The_Doctrine_of_Justification.knit.md

! Paragraph ended before \hypertarget was complete.
<to be read again> 
                   \par 
l.233 

Error: LaTeX failed to compile Buchanan-The_Doctrine_of_Justification.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Buchanan-The_Doctrine_of_Justification.log for more info.
Execution halted

Exited with status 1.
```

**Comment by jtbayly** [comment]
Interesting. That smells like a Pandoc bug, because even multi-paragraph footnotes work fine in the HTML and ePub versions.

**Comment by jtbayly** [comment]
Filed a bug report here: 
https://github.com/jgm/pandoc/issues/6733

I also updated our documentation.
